# Generated by Django 3.0.8 on 2020-07-23 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data do preparo')),
                ('dirigente', models.CharField(max_length=100, verbose_name='M.Dirigente')),
                ('assistente', models.CharField(max_length=100, verbose_name='M.Assistente')),
                ('total_mariri', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total mariri')),
                ('total_chacrona', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total mariri')),
                ('mariri_panela', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total mariri')),
                ('chacrona_panela', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total mariri')),
                ('observacoes', models.TextField(blank=True, max_length=250, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preparo',
                'verbose_name_plural': 'Preparos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_tachada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo Tachada')),
            ],
            options={
                'verbose_name': 'tipo_tachada',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tachada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tachada', models.IntegerField(verbose_name='Num. Tachada')),
                ('qtde_panelas', models.IntegerField(verbose_name='Num. Panelas')),
                ('hora_entrada', models.TimeField(verbose_name='Hora Entrada')),
                ('hora_fervura', models.TimeField(blank=True, verbose_name='Hora Fervura')),
                ('hora_saida', models.TimeField(blank=True, verbose_name='Hora Saída')),
                ('agua_panela', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Total água')),
                ('litros_vegetal', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Litros Vegetal')),
                ('observacoes', models.TextField(blank=True, max_length=250, verbose_name='Observações')),
                ('preparo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Preparo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipo_tachada')),
            ],
            options={
                'verbose_name': 'Tachada',
                'verbose_name_plural': 'Tachadas',
                'ordering': ['id'],
            },
        ),
    ]
