# Generated by Django 3.0.8 on 2020-07-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparo',
            name='chacrona_panela',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Cacrona/Panela'),
        ),
        migrations.AlterField(
            model_name='preparo',
            name='mariri_panela',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Mariri/Panela'),
        ),
        migrations.AlterField(
            model_name='preparo',
            name='total_chacrona',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total chacronai'),
        ),
    ]
