# Generated by Django 3.0.8 on 2020-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200725_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tachada',
            name='total_chacrona',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Total Chacrona'),
        ),
        migrations.AddField(
            model_name='tachada',
            name='total_mariri',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Total Mariri'),
        ),
        migrations.AlterField(
            model_name='tachada',
            name='agua_panela',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Total água'),
        ),
        migrations.AlterField(
            model_name='tachada',
            name='hora_fervura',
            field=models.TimeField(null=True, verbose_name='Hora Fervura'),
        ),
        migrations.AlterField(
            model_name='tachada',
            name='hora_saida',
            field=models.TimeField(null=True, verbose_name='Hora Saída'),
        ),
        migrations.AlterField(
            model_name='tachada',
            name='litros_vegetal',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Litros Vegetal'),
        ),
        migrations.AlterField(
            model_name='tachada',
            name='observacoes',
            field=models.TextField(max_length=250, null=True, verbose_name='Observações'),
        ),
    ]
