# Generated by Django 3.0.8 on 2020-07-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20200728_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='tachada',
            name='chacrona_panela',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Chacrona/Panela'),
        ),
        migrations.AddField(
            model_name='tachada',
            name='mariri_panela',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Mariri/Panela'),
        ),
    ]
